[package]
name = "frontend_terminal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chip_8_core = { path = "../" }
crossterm = { version = "0.28.1", features = ["event-stream"] }
